#' simulation
#'
#' Central nervous system simulation data generated by stochastic differential equation
#'
#' @examples
#'   head(simulation)
"simulation"


#' crest
#'
#' Murine neural crest data,doi: 10.1126/science.aas9536
#'
#' @examples
#'   head(crest)
"crest"


#' hepatoblast
#'
#' Hepatoblast differentiation data,doi: 10.1002/hep.29353
#'
#' @examples
#'   head(hepatoblast)
"hepatoblast"
